services:
  api:
    build: .             # Membangun image dari Dockerfile di folder ini
    container_name: book-review-container
    ports:
      - "9494:3000"      # Mapping port komputer:container
    env_file:
      - .env             # Otomatis membaca file .env Anda
    restart: always      # Restart otomatis jika crash